# Example docker-compose for testing
db:
  image: postgres:latest
  ports:
    - "5432:5432"
api-prod:
  build: .
  volumes:
    - /Users/paoc/test:/test
  ports:
    - "8000:8000"
  command: /sbin/my_init
  environment:
  - DATABASE_HOST=192.168.99.666
  - DATABASE_NAME=postgres
  - DATABASE_USER=postgres
  - DATABASE_PASSWORD=NIL
  - DATABASE_PORT=5432